cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('detail',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove')
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerce_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/',include('accounts.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from ecommerce_app.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return self.product

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from ecommerce_app.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Benne&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
 <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/base2.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Benne&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
 <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Welcome to the cart store where you can buy awesome items....
{% endblock %}
{% block title %}
   Cart-shop your favourite!!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart is empty</h1>
        <br>
        <p class="text-center">Please click<a href="{% url 'allProdCat' %}"> here</a> </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
             <tr>
                 <td>
                     <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" class="float-left rounded custom_image"> </a>
                 </td>
                 <td class="text-left">
                     {{cart_item.product.name}}
                     <br>
                     SKU: {{cart_item.product.id}}
                     <br>
                     Unit price: {{cart_item.product.price}}
                     <br>
                     QTY:{{cart_item.quantity}} * ${{cart_item.product.price}}
                 </td>
                 <td>
                     {{cart_item.subtotal}}
                 </td>
                 {% if cart_item.quantity < cart_item.product.stock %}
                 <td>
                     <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                     <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                     <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                 </td>
                 {% else %}
                 <td>
                     &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                       <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>

                 </td>
                 {% endif %}

             </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>Checkout</th></tr></thead>
            <tbody>
            <tr>
            <td>
                Please review your shopping cart items before proceeding with the order payment</td></tr>
            <tr>
            <td class="text-left">
                Your total is <strong>${{total}}</strong></td></tr></tbody></table>
          <div class="mx-auto">
              <a href="{% url 'allProdCat' %}" class="btn btn-secondary btn-block my_custom_botton">Continue shopping</a>
</div>
      </div></div><br>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
       {{category.desc|truncatewords:155}}
    {% else %}
       welcome to the cart store where you can buy awesome items...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
       {{category.name}}-shop cart
    {% else %}
       see our collections-shop cart
    {% endif %}
{% endblock %}
{% block content %}

    {% if category %}
       <div class="row my_row_class">
           <div class="mx-auto">
               <p><a href="{% url 'allProdCat' %}">Our product collections</a>{{category.name}} </p>
           </div>
       </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
      <center><img class="my_image" src="{{category.img.url}}" alt="{{category.name}}" style="width:500px;height:500px"></center>
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
        <div>
            <center><img class="my_image my_image_padding" src="{% static 'img/swera.png' %}" alt="" style="width:1350px;height:500px"></center>
        </div>
<br>

<div>
    <h1 class="text-center my_title">
        Our Products Collections
    </h1>
    <p class="text-justify">
    Online shopping is a form of electronic commerce which allows consumers to directly buy goods or services from a seller over the Internet using a web browser or a mobile app. ... Online stores usually enable shoppers to use "search" features to find specific models, brands or items.
    </p>
</div>
{% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" style="width:280px;height:280px"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
             <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/footer.html
 <br><br>
<div class="footer navbar-fixed-bottom my_footer">

    <h4 class="text-center">
        &copy;....All Rights Reserved
    </h4>
</div>

templates/header.html
{% load static %}
<div>
    <center>
      <img src="{% static 'img/Ash Round Border Fashion Logo.png' %}"  style="width:100px;height:100px" alt="">
    </center>
</div>

<div>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="">
    </center>
</div>

templates/home.html
{% extends 'base2.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
       {{category.desc|truncatewords:155}}
    {% else %}
       welcome to the cart store where you can buy awesome items...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
       {{category.name}}-shop cart
    {% else %}
       see our collections-shop cart
    {% endif %}
{% endblock %}
{% block content %}

        <div>
            <center><img class="my_image my_image_padding" src="{% static 'img/swera.png' %}" alt="" style="width:1350px;height:500px"></center>
        </div>
<br>
<div>
    <h1 class="text-center my_title">
        Our Products Collections
    </h1>
    <p class="text-justify">
    Online shopping is a form of electronic commerce which allows consumers to directly buy goods or services from a seller over the Internet using a web browser or a mobile app. ... Online stores usually enable shoppers to use "search" features to find specific models, brands or items.
    </p>
</div>
 <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">


            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'assets/images/1.jpeg' %}" alt="" style="width:300px;height:300px"></a>
              <div class="down-content">
                <a href="#"><h4>Girls full length party dress</h4></a>
                <h6>$25.75</h6>
                <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (24)</span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'assets/images/2.jpeg' %}" alt="" style="width:300px;height:300px"></a>
              <div class="down-content">
                <a href="#"><h4>Long top</h4></a>
                <h6>$30.25</h6>
                <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (21)</span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'assets/images/3.jpeg' %}" alt="" style="width:300px;height:300px"></a>
              <div class="down-content">
                <a href="#"><h4>Men Regular Fit Casual Shirt</h4></a>
                <h6>$20.45</h6>
                <p>Sixteen Clothing is free CSS template provided by TemplateMo.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (36)</span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'assets/images/s.jpeg' %}" alt="" style="width:300px;height:300px"></a>
              <div class="down-content">
                <a href="#"><h4>Women A-line Black Dress</h4></a>
                <h6>$15.25</h6>
                <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (48)</span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'assets/images/5.jpeg' %}" alt="" style="width:300px;height:300px"></a>
              <div class="down-content">
                <a href="#"><h4>Sports Running Shoes For Men </h4></a>
                <h6>$12.50</h6>
                <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (16)</span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'assets/images/a.jpeg' %}" alt="" style="width:300px;height:300px"></a>
              <div class="down-content">
                <a href="#"><h4>Women Solid Dark Green Skirt</h4></a>
                <h6>$22.50</h6>
                <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                </ul>
                <span>Reviews (32)</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/login.html
{% extends 'base2.html' %}
{% load static %}
{% block metadescription %}
       {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
       {{product.name}}-shop cart
{% endblock %}
{% block content %}
 {% if category %}
       <div class="row my_row_class">
           <div class="mx-auto">
               <p><a href="{% url 'allProdCat' %}">Our product collections</a>{{category.name}} </p>
           </div>
       </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
       <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
        <div>
            <center><img class="my_image my_image_padding" src="{% static 'img/swera.png' %}" alt="" style="width:1350px;height:500px"></center>
        </div>
<br>
{% endif %}
<form action="login" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="form-group text-center"> <input class="form-control" type="text" name="username" placeholder="username"></div>
        <div class="form-group text-center"> <input class="form-control" type="password" name="password" placeholder="password"></div>
      <center><input class="btn btn-success" type="submit" value="Login"></center>
    </div>
</form>
{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'allProdCat' %}">All Products</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}

        </div>
      </li>
      {% if user.is_authenticated %}
 <li class="nav-link">Hai {{user.first_name}}</li>
 <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
{% else %}
 <li><a  class="nav-link" href="{% url 'register' %}">Registration</a></li>
 <li><a class="nav-link" href="{% url 'login' %}">Login</a></li>
{% endif %}

          {% if item_count > 0 %}
       <li class="nav-item active">
        <a class="nav-link" href="cart_detail"><i class="fas fa-shopping-cart">{{item_count}}</i></a>

      {% endif %}

</li>
    </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


<li><a  class="nav-link" href="/">Home</a></li>
      {% if user.is_authenticated %}
 <li class="nav-link">Hai {{user.first_name}}</li>
 <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
{% else %}
 <li><a  class="nav-link" href="{% url 'register' %}">Registration</a></li>
 <li><a class="nav-link" href="{% url 'login' %}">Login</a></li>
{% endif %}
          {% if item_count > 0 %}
       <li class="nav-item active">
        <a class="nav-link" href="cart_detail"><i class="fas fa-shopping-cart">{{item_count}}</i></a>

      {% endif %}
</li>
    </ul>
      <form class="form-inline my-2 my-lg-0" action="" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
       {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
       {{product.name}}-shop cart
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
    <div class="col-md-8">
        <div class="banner">
           <p><a href="{% url 'allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}"></a>{{product.name}} </p>
        </div>
    </div>
</div>
    <div class="row mx-auto">
        <div class="col-md-4 ">
            <img class="align-self-center mr-3" src="{{product.img.url}}" alt="Generic placeholder image" style="width:300px;height:300px">
        </div>
        <div class="col-md-4 ">
         <h5 class="mt-0">{{product.name}}</h5>
    <p>${{product.price}}</p>
    <p class="text-justify">{{product.desc}}</p>
      {% if product.stock <= 0 %}
      <p><b>out of stock</b></p>
      {% else %}
      <br>
      <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-dark">Add to cart</a>
      {% endif %}
        </div>
    </div>

</div>
{% endblock %}

templates/registration.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
 {% if category %}
       <div class="row my_row_class">
           <div class="mx-auto">
               <p><a href="{% url 'allProdCat' %}">Our product collections</a>{{category.name}} </p>
           </div>
       </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
       <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
        <div>
            <center><img class="my_image my_image_padding" src="{% static 'img/swera.png' %}" alt="" style="width:1350px;height:500px"></center>
        </div>
<br>
{% endif %}
<form action="register" method="post">
     {% csrf_token %}
    <div class="container">
     <div class="form-group text-center"><input class="form-control" type="text" name="username" placeholder="username"></div>

        <div class="form-group text-center"><input class="form-control" type="text" name="firstname" placeholder="Firstname"></div>
        <div class="form-group text-center"><input class="form-control" type="text" name="lastname" placeholder="Lastname"></div>
        <div class="form-group text-center"> <input class="form-control" type="email" name="email" placeholder="Email"></div>
        <div class="form-group text-center"> <input class="form-control" type="password" name="password1" placeholder="Password"></div>
        <div class="form-group text-center"> <input class="form-control" type="password" name="password2" placeholder="Password"></div>
     <center> <input  class="btn btn-success" type="submit" value="Register"></center>

</div>
</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</div>
{% endblock %}

templates/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>common1</h1>
{% if user.is_authenticated %}
<h1>before</h1>

<h2>after</h2>
{% endif %}
<h1>common2</h1>


</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
       {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
       {{product.name}}-shop cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:{{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in category %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found...</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}